<?php
$db="localhost";
$username="root";
$password="";
$dbname="beltiewebdb";
$conn=mysqli_connect($db,$username,$password,"$dbname");
if(!$conn)
{
echo("Error".mysqli_error($conn));
}
session_start();
?>